name: neural-network-projects-python
channels:
  - conda-forge
dependencies:
  - pandas==0.23.4
  - numpy==1.15.2
  - matplotlib==3.0.2
  - Keras==2.2.4
  - opencv==3.4.2
  - seaborn==0.9.0
  - scikit-learn==0.20.2
  - mkl-service==1.1.2
  - theano==1.0.3
